### PR TITLE
removed misleading content from the README.md

### LINKED ISSUE #793: Mislead contents in Readme
**What happened**
Mislead contents in Readme (https://github.com/cloud-barista/cb-tumblebug/blob/main/README.md).

https://github.com/cloud-barista/cb-tumblebug/blame/main/README.md#L422
https://github.com/cloud-barista/cb-tumblebug/blame/main/README.md#L423

```
  - CB-MapUI 를 통해 MCIS 형상 확인 및 제어 가능
    - `./command-mcis.sh -n shson -f ../testSetCustom.env`  # MCIS의 모든 VM에 IP 및 Hostname 조회를 수행
```

are mislead contents.

**Proposed solution**

Remove 
https://github.com/cloud-barista/cb-tumblebug/blame/main/README.md#L422
https://github.com/cloud-barista/cb-tumblebug/blame/main/README.md#L423

```diff
-  - CB-MapUI 를 통해 MCIS 형상 확인 및 제어 가능
-    - `./command-mcis.sh -n shson -f ../testSetCustom.env`  # MCIS의 모든 VM에 IP 및 Hostname 조회를 수행
```

### PR DESCRIPTION
**Pull request by MukulKolpe**
Fixes #793 

Removed lines 423-424 from the README.md

### CODE REVIEW

**Comment by seokho-son** [comment]
@MukulKolpe Nice to meet your first PR !! :) Thank you! LGTM.

**Comment by seokho-son** [comment]
@all-contributors please add @MukulKolpe for documentation

**Comment by MukulKolpe** [comment]
Thanks a lot @seokho-son 😀

**Pull request merged**
