### PR TITLE
Add skip logging middleware by uri rule

### PR DESCRIPTION
**Pull request by seokho-son**
Very first code ;)
skipPatterns should be injected from a higher level function.

### CODE REVIEW

**Review by yunkon-kim — COMMENTED** [review]
@seokho-son 

Skipping some patterns is very useful! For this purpose, it would be good to use Skipper as suggested. 

Additionally, we should modify some code in `server.go`.
```diff
-      e.Use(middlewares.Zerologger())
+	skipPatterns := []string{
+		"/tumblebug/api",
+		"/mcis?option=status",
+	}
+	e.Use(middlewares.Zerologger(skipPatterns))
```

**Comment by seokho-son** [comment]
Thanks @yunkon-kim 
Applied your suggestion! Super nice.

**Review by yunkon-kim — APPROVED** [review]
@seokho-son LGTM👍

**Pull request merged**
