### PR TITLE
Update workflows for CI and CD

### PR DESCRIPTION
**Pull request by yunkon-kim**
This PR will update the workflows for CI and CD (previously, publish-multi-arch-container-images.yaml and build-amd64-container-image.yaml).
- To make it clear where errors occur, building source code and container image are separated.
- Container images will be published
  - with `semver` and `latest` tags for the stable version. (`latest` will point to the latest `semver` tag.)
  - with `edge` for the unstable version. (When a PR is merged, a container image is created (overwritten) with the `edge` tag, which may not be stable.)

It has the advantage of 
- utilizing stable images with the `semver` and `latest` tag, and
- testing the recent developments with the `edge` tag.

### CODE REVIEW

**Comment by seokho-son** [comment]
Thanks, @yunkon-kim!

I have a minor question regarding the naming of our workflows:
.github/workflows/continuous-delivery.yaml
.github/workflows/continuous-integration.yaml

How about changing the names to something more intuitive? For instance, simply `build-test` and `publish-container-image`? This might help avoid confusion given that people may have different understandings of CI/CD terms.

**Comment by yunkon-kim** [comment]
@seokho-son First of all, I have no objection to naming ^^ 

I don't think the term CI/CD will be understood much differently. Considering that related features will be added later, I think it would be good to leave it as is. 

However, if related features are not added, I think `CI` should be changed to `build test`. It seems okay to use either term because `publish container image` and `continuous-delivery` can be understood to have almost the same meaning.

**Comment by seokho-son** [comment]
Agreed ! :)

**Pull request merged**
