### PR TITLE
Add workflow for automatic PR merge

### PR DESCRIPTION
**Pull request by seokho-son**
### This PR will automate PR merge by checking merge conditions.

This workflow consists of 3 main steps.

For each event on a comment (in PR)

1. Check author_association is OWNER
1. Apply 'approved' label when OWNER left '/approve' comment
1. AutoMerging if this PR has MERGE_LABELS: approved, lgtm (not wip, hold)

You can check demo from [here](https://github.com/seokho-son/docs/pull/18)

### CODE REVIEW

**Comment by seokho-son** [comment]
cc @hermitkim1

**Comment by jihoon-seo** [comment]
이 PR 을 merge 하기 전이라서 그런지,
아직 auto-merge 가 동작하지 않아서,
수동으로 merge 하겠습니다 :)

**Pull request merged**
