### PR TITLE
Add associatedObjList mgmt feature for TB MCIR objects

### LINKED ISSUE #348: TODO: Add associatedObjectList in TB objects
Suggestion from @seokho-son 
https://github.com/cloud-barista/cb-tumblebug/pull/347#pullrequestreview-568827067

> ```
> in-use Count 운영 방식으로 다음의 2가지가 있습니다.
> 1안: VM 을 생성할 때, 링크되는 sshKey 의 inUseCount 필드를 +1 하고,
> VM 을 삭제할 때, 링크된 sshKey 의 inUseCount 필드를 -1 한다.
> 2안: 특정 TB sshKey object 에 대해 GetInUseCount 함수를 호출하면, 모든 VM 을 조회해서,
> 그 중 특정 TB sshKey object 와 링크되어 있는 VM 의 수를 출력
> (특정 TB sshKey object 에 대해 Get 했을 때에도 같은 방법으로 inUseCount 값을 조회하여 출력)
> 이 PR에서는 sshKey 에 대해 1안으로 구현했습니다.
> 그런데 +1, -1 동작이 항상 완벽할 수는 없어서 Count 숫자가 맞지 않는 상황이 발생할 수 있습니다.
> ```
> 
> 저도 현재는 1안을 선호합니다.
> 다만, 동작이 항상 완벽할 수는 없는 부분 (locking 처리 문제 등등?)은 오류 발생시 보정을 하는게 좋지 않을까 싶습니다. (오류 예시: vm에 사용되고 있는 자원 삭제시, CSP에서 삭제 거절하는 케이스 등)
> 
> 추가적으로, inUse 를 숫자로 제공하는 방법도 있겠지만,
> 해당 MCIR을 사용하는 다른 자원을 리스트로 기록하여 관리하는 방법도 있지 않을까요?
> 
> 예를 들면,
> 
> ```
>    "connectionName" : "aws-us-east-1",
>    "publicKey" : "",
>    "associatedObjectList" : [mcis/mcis-01/vm/vm-04, 
>                                            mcis/mcis-01/vm/vm-07, 
>                                            mcis/mcis-034/vm/vm-01, 
>                                            mcis/mcis-012/vm/vm-01 ]
> ```
> 
> 그리고 inUse 확인 시, 해당 리스트의 count 값을 활용.
> 
> 이렇게 하면, 문제가 발생하는 경우, 추적도 용이하지 않을까요?
> 
> 일단, 현재 코드를 기반으로도 간단히 의견 드립니다.. ^^

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Resolves #348
- Add associatedObjList mgmt feature for TB MCIR objects
  - image
  - securityGroup
  - spec
  - sshKey
  - vNet
- Apply some suggestions from `golangci-lint`
- Add some comments for exported functions

---

[Test results]

```
❯ ./get-vNet.sh aws 1 jhseo
####################################################################
## 3. vNet: Get
####################################################################
[Test for AWS]
{
...
   "associatedObjectList" : [
      "/ns/ns-01/mcis/aws-us-east-1-jhseo/vm/aws-us-east-1-jhseo-01"
   ],
...
}
```

```
❯ ./testGetAssoCount.sh aws 1 jhseo
####################################################################
## 3. vNet : Get association count
####################################################################
[Test for AWS]
{"associatedObjectCount":1}
```

---

```
❯ ./get-securityGroup.sh aws 1 jhseo
####################################################################
## 4. SecurityGroup: Get
####################################################################
[Test for AWS]
{
...
   "associatedObjectList" : [
      "/ns/ns-01/mcis/aws-us-east-1-jhseo/vm/aws-us-east-1-jhseo-01"
   ],
...
}
```

```
❯ ./testGetAssoCount.sh aws 1 jhseo
####################################################################
## 4. securityGroup : Get association count
####################################################################
[Test for AWS]
{"associatedObjectCount":1}
```

---

```
❯ ./get-sshKey.sh aws 1 jhseo       
####################################################################
## 5. sshKey: Get
####################################################################
[Test for AWS]
{
...
   "associatedObjectList" : [
      "/ns/ns-01/mcis/aws-us-east-1-jhseo/vm/aws-us-east-1-jhseo-01"
   ],
...
}
```

```
❯ ./testGetAssoCount.sh aws 1 jhseo
####################################################################
## 5. sshKey: Get association count
####################################################################
[Test for AWS]
{"associatedObjectCount":1}
```

---

```
❯ ./get-image.sh aws 1 jhseo 
####################################################################
## 6. image: Get
####################################################################
[Test for AWS]
{
...
   "associatedObjectList" : [
      "/ns/ns-01/mcis/aws-us-east-1-jhseo/vm/aws-us-east-1-jhseo-01"
   ],
...
}
```

```
❯ ./testGetAssoCount.sh aws 1 jhseo
####################################################################
## 6. image : Get association count
####################################################################
[Test for AWS]
{"associatedObjectCount":1}
```

---

```
❯ ./get-spec.sh aws 1 jhseo       
####################################################################
## 7. spec: Get
####################################################################
[Test for AWS]
{
...
   "associatedObjectList" : [
      "/ns/ns-01/mcis/aws-us-east-1-jhseo/vm/aws-us-east-1-jhseo-01"
   ],
...
}
```

```
❯ ./testGetAssoCount.sh aws 1 jhseo
####################################################################
## 7. spec : Get association count
####################################################################
[Test for AWS]
{"associatedObjectCount":1}
```

### CODE REVIEW

**Comment by jihoon-seo** [comment]
You can see that the `associatedObjectCount` value's type is not `string` but number (`int`).
```JSON
{"associatedObjectCount":1}
```

---

(In the future) If `string` is preferred, we can achieve this by modifying:

[From]
```Go
mapA := map[string]int{"associatedObjectCount": associatedObjectCount}
```

[To]
```Go
mapA := map[string]string{"associatedObjectCount": associatedObjectCount}
```

**Review by seokho-son — COMMENTED** [review]
LGTM입니다. 마이너한 의견은 꼭 지금 반영할 필요는 없겠습니다.
제공해주신 테스트 스크립트 기반으로 저도 사용해보겠습니다... ^-^

**Pull request merged**
