### PR TITLE
Apply zerolog to some parts of mcis dynamic provision

### PR DESCRIPTION
**Pull request by seokho-son**
Found 
 - #1477 is very useful !

Trying to apply it to some parts of mcis dynamic provision.

### CODE REVIEW

**Comment by seokho-son** [comment]
PTAL: @yunkon-kim :)

**Review by yunkon-kim — APPROVED** [review]
@seokho-son LGTM!

I'd like to share two useful usages.
- `log.Error().Err(err).Msg("")` is possible if the `err` object has a clear error message:
  - https://github.com/rs/zerolog?tab=readme-ov-file#error-logging
- Contextual logging (i.e., key-value type) 
  - https://github.com/rs/zerolog?tab=readme-ov-file#contextual-logging

**Comment by seokho-son** [comment]
@yunkon-kim 
So.. 

err := fmt.Errorf("Failed to get the vNet " + vmReq.VNetId + " from " + vmReq.ConnectionName)
log.Error().Err(err).Msg("Failed to get the vNet")

--> `log.Error().Err(err).Msg("")` is a better usage?

**Comment by yunkon-kim** [comment]
@seokho-son It depends on errors. The current code looks fine to me. 

Here's an example code and result: 

```go
err := fmt.Errorf("error message from err objects")
	log.Error().Err(err).Msg("my error message")
```

Console
image

Log file
```json
{"level":"error","error":"error message from err objects","time":"2024-04-01T17:15:54+09:00","caller":"/home/ubuntu/dev/cloud-barista/cb-tumblebug/src/api/rest/server/server.go:88","message":"my error message"}
```

**Comment by seokho-son** [comment]
@yunkon-kim Thanks! then, let's keep the current. Please approve (merge) if it is ok. :)

**Pull request merged**
