### PR TITLE
Use Resty for REST client part

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Tested with
  - `test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`
  - `test/official/sequentialFullTest/cleanAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`

---

[Done]
- src/core/common/utility.go
  - func GetConnConfig(ConnConfigName string) (ConnConfig, error)
  - func GetConnConfigList() (ConnConfigList, error)
  - func GetRegion(RegionName string) (Region, error)
  - func GetRegionList() (RegionList, error)
- src/core/mcir/securitygroup.go
  - func CreateSecurityGroup(nsId string, u *TbSecurityGroupReq) (TbSecurityGroupInfo, error)
- src/core/mcir/spec.go
  - func LookupSpecList(connConfig string) (SpiderSpecList, error)
  - func LookupSpec(connConfig string, specName string) (SpiderSpecInfo, error)
- src/core/mcir/sshkey.go
  - func CreateSshKey(nsId string, u *TbSshKeyReq) (TbSshKeyInfo, error)
- src/core/mcir/vnet.go
  - func CreateVNet(nsId string, u *TbVNetReq) (TbVNetInfo, error)

---

[Didn't]
(maybe next time)
(How to find: Search `Do(` in `src/core/`)
- src/core/mcir/common.go
  - func DelResource(nsId string, resourceType string, resourceId string, forceFlag string) error
- src/core/mcir/image.go
  - func LookupImageList(connConfig string) (SpiderImageList, error)
  - func LookupImage(connConfig string, imageId string) (SpiderImageInfo, error)
- src/core/mcis/control.go
  - func CallMilkyway(wg *sync.WaitGroup, vmList []string, nsId string, mcisId string, vmId string, vmIp string, action string, option string, results *BenchmarkInfoArray)
  - func CreateVm(nsId string, mcisId string, vmInfoData *TbVmInfo) error
  - func ControlVmAsync(wg *sync.WaitGroup, nsId string, mcisId string, vmId string, action string, results *ControlVmResultWrapper) error
  - func ControlVm(nsId string, mcisId string, vmId string, action string) error
  - func GetVmStatus(nsId string, mcisId string, vmId string) (TbVmStatusInfo, error)
  - func GetVmCurrentPublicIp(nsId string, mcisId string, vmId string) (TbVmStatusInfo, error)
- src/core/mcis/monitor.go
  - func CallMonitoringAsync(wg *sync.WaitGroup, mcisID string, vmID string, vmIP string, userName string, privateKey string, method string, cmd string, returnResult *[]SshCmdResult)
  - func CallGetMonitoringAsync(wg *sync.WaitGroup, mcisID string, vmID string, method string, cmd string, returnResult *[]SshCmdResult)

### CODE REVIEW

**Comment by jihoon-seo** [comment]
[TODO]
- All files
  - Add `err` check logic after `resp, _ := client.R().`
  - Make it tidy
  - Consider removing StatusCode check code ([Resty `SetResult()` function](https://godoc.org/github.com/go-resty/resty#Request.SetResult) checks status code.)
- src/core/common/utility.go
  - json.Unmarshal -> type assertion (`resp.Result().(*Struct)`)

**Comment by jihoon-seo** [comment]
[Consider removing StatusCode check code ([Resty `SetResult()` function](https://godoc.org/github.com/go-resty/resty#Request.SetResult) checks status code.)]

현재 코드가 다음과 같이 되어 있습니다.
```Go
resp, err := client.R().
	SetResult(&ConnConfig{}).
	//SetError(&SimpleMsg{}).
	Get(url)

if err != nil {
	CBLog.Error(err)
	content := ConnConfig{}
	err := fmt.Errorf("an error occurred while requesting to CB-Spider")
	return content, err
}

fmt.Println(string(resp.Body())) // for debug

fmt.Println("HTTP Status code " + strconv.Itoa(resp.StatusCode()))
switch {
case resp.StatusCode() >= 400 || resp.StatusCode() < 200:
	err := fmt.Errorf(string(resp.Body()))
	CBLog.Error(err)
	content := ConnConfig{}
	return content, err
}

temp, _ := resp.Result().(*ConnConfig)
return *temp, nil
```

로직은 다음과 같습니다.
1. Get()
2. Get() 에 대한 err 가 있으면 `return emptyStruct, err`
3. Status code 가 비정상이면 `return emptyStruct, err`
4. (2번과 3번에서 통과되었으면) interface conversion (type assertion) 하고 `return *temp, nil`

---

Resty `SetResult()` 함수는
'status code 가 200 ~ 299 일 때 Unmarshal 할 struct 를 지정하는 함수' 일 뿐
status code 가 200 ~ 299 이외일 때 다른 동작을 하도록 지정할 수는 없는 것을 확인하였습니다.

이에
현재로서는 위의 로직 중 3번에 해당하는 코드가 필요하여
그대로 두었습니다.

---

[Done in 2nd commit]
- All files
  - ~~Add `err` check logic after `resp, _ := client.R().`~~
  - ~~Make it tidy~~ (a little bit)
- src/core/common/utility.go
  - ~~json.Unmarshal -> type assertion (`resp.Result().(*Struct)`)~~
- src/core/mcir/common.go
  - ~~func DelResource(nsId string, resourceType string, resourceId string, forceFlag string) error~~
- src/core/mcir/image.go
  - ~~func LookupImageList(connConfig string) (SpiderImageList, error)~~
  - ~~func LookupImage(connConfig string, imageId string) (SpiderImageInfo, error)~~

[Didn't]
(maybe next time)
(How to find: Search `Do(` in `src/core/`)
- src/core/mcis/control.go
  - func CallMilkyway(wg *sync.WaitGroup, vmList []string, nsId string, mcisId string, vmId string, vmIp string, action string, option string, results *BenchmarkInfoArray)
  - func CreateVm(nsId string, mcisId string, vmInfoData *TbVmInfo) error
  - func ControlVmAsync(wg *sync.WaitGroup, nsId string, mcisId string, vmId string, action string, results *ControlVmResultWrapper) error
  - func ControlVm(nsId string, mcisId string, vmId string, action string) error
  - func GetVmStatus(nsId string, mcisId string, vmId string) (TbVmStatusInfo, error)
  - func GetVmCurrentPublicIp(nsId string, mcisId string, vmId string) (TbVmStatusInfo, error)
- src/core/mcis/monitor.go
  - func CallMonitoringAsync(wg *sync.WaitGroup, mcisID string, vmID string, vmIP string, userName string, privateKey string, method string, cmd string, returnResult *[]SshCmdResult)
  - func CallGetMonitoringAsync(wg *sync.WaitGroup, mcisID string, vmID string, method string, cmd string, returnResult *[]SshCmdResult)

---

- Tested with
  - `test/official/sequentialFullTest/testAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`
  - `test/official/sequentialFullTest/cleanAll-mcis-mcir-ns-cloud.sh aws 1 jhseo`

**Comment by seokho-son** [comment]
@jihoon-seo 좋아보입니다.. ^^
주석 처리한 내용은 코드의 간결함을 위해서 삭제하는 것이 어떨지 문의 드립니다.

**Comment by jihoon-seo** [comment]
@jihoon-seo 주석 처리한 코드를 삭제 완료 했습니다!

**Comment by seokho-son** [comment]
Thank you !! I am going to merge this PR!

**Pull request merged**
