### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jayita10**
Fixed issue #796

### CODE REVIEW

**Comment by seokho-son** [comment]
Thank you @Jayita10. Looks good to me !!

CB-Tumblebug welcomes improvements from all contributors, new and experienced!
We look forward to further contributions from you~! :)

**Comment by seokho-son** [comment]
@all-contributors please add @Jayita10 documentation

**Comment by Jayita10** [comment]
> Thank you @Jayita10. Looks good to me !!
> 
> CB-Tumblebug welcomes improvements from all contributors, new and experienced!
> We look forward to further contributions from you~! :)

I think the same should be change [here](https://github.com/cloud-barista/cb-tumblebug/blob/main/i18n/README-EN.md) also. @seokho-son

**Comment by seokho-son** [comment]
@Jayita10 Thank you for the suggestion !!

https://github.com/cloud-barista/cb-tumblebug/blob/main/i18n/README-EN.md is a Readme in English. However, WIP.

Whereas the document is WIP, I think we can keep sync as you suggested !

Cloud you contribute to this issue too? :)

**Pull request merged**
