### PR TITLE
Fix code format according to gofmt

### PR DESCRIPTION
**Pull request by seokho-son**
Fix code format according to gofmt.

I applied gofmt to all *.go files. 

Check recommendation by `gofmt -d ./` 
And apply them by `gofmt -w ./`

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Since [Auto-merge workflow run](https://github.com/cloud-barista/cb-tumblebug/actions/runs/508586767) was skipped,
I will merge manually.
(@seokho-son 오토머지가 되어야 할 것 같은데, 안 되네요..)

**Comment by seokho-son** [comment]
> Since [Auto-merge workflow run](https://github.com/cloud-barista/cb-tumblebug/actions/runs/508586767) was skipped,
> I will merge manually.
> (@seokho-son 오토머지가 되어야 할 것 같은데, 안 되네요..)

조건이 만족되지 않아서, approve label 만 붙고, auto-merge는 skip 된 것으로 보이네요.
빌드 테스트 (check) 가 완료되고 approve 되어야 할 것 같습니다 ~

빌드 테스트 완료 후, approve 코멘트를 다시 남겨주세요^^

**Pull request merged**
