### PR TITLE
Adopt XORM (to avoid using raw SQL queries)

### PR DESCRIPTION
**Pull request by jihoon-seo**
- ORM: Object-Relational Mapping
- XORM is a Simple & Powerful ORM Framework for Go Programming Language
- 변경사항
  - SQL CreateTable 부분이 간결해졌습니다. 
    (XORM이 `TbImageInfo`, `TbSpecInfo` struct의 definition대로 Table 생성)
  - SQL INSERT (`registerImage/Spec`) 부분이 간결해졌습니다. 
    (XORM이 `TbImageInfo`, `TbSpecInfo` 객체를 RDB에 자동으로 처리하여 입력)
  - SQL DELETE (`unregisterImage/Spec`) 부분이 간결해졌습니다.
  - SQL UPDATE (`updateSpec`) 부분이 간결해졌습니다.
    (참고: `Update()` updates one or more records, default will update non-empty and non-zero fields.)
  - SQL SELECT (`searchImage`, `filterSpecs`, `filterSpecsByRange`) 부분이 간결해졌습니다.
  - Updated `searchImage`, `filterSpecs`, `filterSpecsByRange` codes accordingly.

### CODE REVIEW

**Comment by seokho-son** [comment]
XORM이 bsd 3-clause 인듯한데 사용하는 것에 문제는 없을까요? 
혹시 다른 라이브러리로 변경은 수월하려나요?

**Comment by jihoon-seo** [comment]
> XORM이 bsd 3-clause 인듯한데 사용하는 것에 문제는 없을까요?

훔 라이센스를 못봤네요.. 조사가 필요할 것 같습니다.

> 혹시 다른 라이브러리로 변경은 수월하려나요?

아마 수월할 것 같습니다. 😊

**Comment by seokho-son** [comment]
@jihoon-seo 수월한 상황이라면, 일단 머지 후에 대안을 찾아볼까요? ^^

**Comment by jihoon-seo** [comment]
Is BSD license compatible with Apache?
https://softwareengineering.stackexchange.com/questions/40561/is-bsd-license-compatible-with-apache
> Short answer: Yes. The Apache Software License was based in large part on BSD and MIT style licenses. The common understanding while I was working on Apache code a while back was that you could incorporate BSD, MIT, and similar licensed libraries but you could not do the same for GPL based licenses.

> The best answer for this can be found in the apache third party license policy. This is the policy that all apache projects have to follow when using libs with other licenses. As you can see BSD is listed in Category A - Authorized licenses. So it should be no problem using this license. You can also find policies for other licenses here which is quite helpful. In fact I think the Apache policy may also be a good starting point for you own licensing policy if you work for a company.
http://www.apache.org/legal/resolved.html

**Pull request merged**
