### PR TITLE
Update assets (spec & image)

### PR DESCRIPTION
**Pull request by jihoon-seo**
참고:
- https://az-vm-image.info/

### CODE REVIEW

**Comment by seokho-son** [comment]
이렇게 빨리.. 역시 대단하십니당! :) 감사감사

**Review by seokho-son — APPROVED** [review]

**Comment by seokho-son** [comment]
"image: azure-uaenorth-windowsserver2012r2  [Failed] {\"message\":\"compute.VirtualMachineImagesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\\\"InvalidParameter\\\" Message=\\\"The value of parameter version is invalid.\\\" Target=\\\"version\\\"\"}\n",
    "image: azure-uksouth-debian10  [Failed] {\"message\":\"compute.VirtualMachineImagesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\\\"InvalidParameter\\\" Message=\\\"The value of parameter version is invalid.\\\" Target=\\\"version\\\"\"}\n",
    "image: azure-uksouth-ubuntu18-04",
    "image: azure-uksouth-ubuntu22-04",
    "image: azure-uksouth-windowsserver2012r2  [Failed] {\"message\":\"compute.VirtualMachineImagesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\\\"InvalidParameter\\\" Message=\\\"The value of parameter version is invalid.\\\" Target=\\\"version\\\"\"}\n",
    "image: azure-ukwest-debian10  [Failed] {\"message\":\"compute.VirtualMachineImagesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\\\"InvalidParameter\\\" Message=\\\"The value of parameter version is invalid.\\\" Target=\\\"version\\\"\"}\n",
    "image: azure-ukwest-ubuntu18-04",
    "image: azure-ukwest-ubuntu22-04",
    "image: azure-ukwest-windowsserver2012r2  [Failed] {\"message\":\"compute.VirtualMachineImagesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\\\"InvalidParameter\\\" Message=\\\"The value of parameter version is invalid.\\\" Target=\\\"version\\\"\"}\n",
    "image: azure-westcentralus-debian10  [Failed] {\"message\":\"compute.VirtualMachineImagesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\\\"InvalidParameter\\\" Message=\\\"The value of parameter version is invalid.\\\" Target=\\\"version\\\"\"}\n",
    "image: azure-westcentralus-ubuntu18-04",
    "image: azure-westcentralus-ubuntu22-04",
    "image: azure-westcentralus-windowsserver2012r2  [Failed] {\"message\":\"compute.VirtualMachineImagesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\\\"InvalidParameter\\\" Message=\\\"The value of parameter version is invalid.\\\" Target=\\\"version\\\"\"}\n",
    "image: azure-westeurope-debian10  [Failed] {\"message\":\"compute.VirtualMachineImagesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\\\"InvalidParameter\\\" Message=\\\"The value of parameter version is invalid.\\\" Target=\\\"version\\\"\"}\n",
    "image: azure-westeurope-ubuntu18-04",
    "image: azure-westeurope-ubuntu22-04",
    "image: azure-westeurope-windowsserver2012r2  [Failed] {\"message\":\"compute.VirtualMachineImagesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\\\"InvalidParameter\\\" Message=\\\"The value of parameter version is invalid.\\\" Target=\\\"version\\\"\"}\n",
    "image: azure-westindia-debian10  [Failed] {\"message\":\"compute.VirtualMachineImagesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\\\"InvalidParameter\\\" Message=\\\"The value of parameter version is invalid.\\\" Target=\\\"version\\\"\"}\n",


```
AZURE,azure-switzerlandwest,Debian:debian-10:10:latest,Debian 10
AZURE,azure-germanynorth,Debian:debian-10:10:latest,Debian 10
AZURE,azure-uaecentral,Debian:debian-10:10:latest,Debian 10
AZURE,azure-norwaywest,Debian:debian-10:10:latest,Debian 10
AZURE,azure-francesouth,Debian:debian-10:10:latest,Debian 10
AZURE,azure-australiacentral2,Debian:debian-10:10:latest,Debian 10
AZURE,azure-westus,MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest,Windows Server 2012 R2
AZURE,azure-eastus,MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest,Windows Server 2012 R2
AZURE,azure-northeurope,MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest,Windows Server 2012 R2
```

@jihoon-seo 
cb-tumblebug$ ./scripts/initMultiCloudEnv.sh
를 통해서 해당 PR의 정보로 이미지 및 스펙을 등록하는데
아마 이미지를 latest 로 하면, 
SP 및 드라이버에서 이를 처리하지 못하는 것 같습니다. (latest  이미지에 대한 정보 조회)

흠 이미지 id를 변경하거나, SP를 통해서 개선이 필요해 보이네요.

**Comment by jihoon-seo** [comment]
그렇겠네요.. 😅

다음의 것들은 잘 되려나 모르겠네요..

- `Debian:debian-10:10:0.20220911.1135`
  (https://az-vm-image.info/?cmd=--all+--publisher+debian+--offer+debian-10+--sku+10 에서 
  daily, backports 등 제외한 것 중 최신)
- `MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:9600.20671.221105`
  (https://az-vm-image.info/?cmd=--all+--publisher+MicrosoftWindowsServer+--offer+WindowsServer+--sku+2012-R2-Datacenter 에서
  smalldisk, gen2, zhcn 등 제외한 것 중 최신)

**Comment by seokho-son** [comment]
@jihoon-seo 공유해주신 id는 일단 등록 가능한 것을 확인했습니다. 
전반적으로 개선 방안을 찾으면 좋긴하겠는데, 일단은 공유해주신 id 로 PR 다시 올려두겠습니다! :)

**Pull request merged**
