### PR TITLE
Enable [skip ci] for GitHub Actions

### LINKED ISSUE #359: Suggestion: Use [skip ci] in GitHub Actions
How about supporting [skip ci] for GitHub Actions.

With this, we can skip CI if a commit title includes `[skip ci]`.

I think it is useful for handling bot generated PRs. 

For instance, `allcontributors`-bot includes `[skip ci]` in every commit titles like [this PR](https://github.com/cloud-barista/cb-tumblebug/pull/355/commits).

Rf (How to): https://dev.to/epassaro/use-skip-ci-in-github-actions-1mnf

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Resolves #359 
- Ref (How to): https://dev.to/epassaro/use-skip-ci-in-github-actions-1mnf

### CODE REVIEW

**Comment by seokho-son** [comment]
Soooo fast !
LGTM.

@hermitkim1 could you check this PR ? :)

**Comment by hermitkim1** [comment]
Wow, so fast 🏃 💨 
LGTM

**Comment by seokho-son** [comment]
@all-contributors please add @hermitkim1 for Reviewed Pull Requests

**Comment by seokho-son** [comment]
Approved ! Thank you.

**Comment by seokho-son** [comment]
@all-contributors please add @hermitkim1 for Review

**Comment by jihoon-seo** [comment]
You can see that CI is skipped @ https://github.com/cloud-barista/cb-tumblebug/actions/runs/492582442

**Pull request merged**
