### PR TITLE
use Errorf for error msg

### PR DESCRIPTION
**Pull request by betelgeuse-7**
Use `fmt.Errorf()` for error message on line 483 in src/core/mcis/control.go

Also changed some of the lines with string concetanation in `fmt.Println()` functions, to `fmt.Printf()` lines.

### CODE REVIEW

**Comment by seokho-son** [comment]
This PR closes #766.

@betelgeuse-7 Thank you for the contribution ! I am happy to see the new contributor. :)
The modifications for fmt.Println() concatenation is also LGTM.

**Comment by seokho-son** [comment]
@all-contributors please add @betelgeuse-7 for code

**Comment by betelgeuse-7** [comment]
@seokho-son Thank you! Though I didn't do much, this was fun. Knowing I helped some people -very little- makes me feel good. :)

**Pull request merged**
