### PR TITLE
Add Elastic Stack scripts as a usecase

### PR DESCRIPTION
**Pull request by yunkon-kim**
This PR will provide scripts for the installation, configuration, execution, termination, and removal of Elastic Stack.

The Elastic Stack includes Elasticsearch, Logstash, Kibana (ELK Stack), and Filebeat.

Please take a look at README for a detailed explanation.

### CODE REVIEW

**Comment by yunkon-kim** [comment]
I'm checking issues from Codacy.

**Comment by yunkon-kim** [comment]
I've resolved issues in the scripts.

However, I don't think we need to take care of markdown lint like [this issue](https://app.codacy.com/p/542266/issues/index?resultDataId=131139691550). 

I propose 2 possible options.
1. Disabling markdown lint
2. Setting markdown lint options to suit our markdown usage patterns

**Comment by yunkon-kim** [comment]
@seokho-son Thank you for setting up Codacy to resolve the markdown-lint issues ^^

Additionally, I tested all scripts on my AWS EC2 instance. If you have any test cases or environments for additional script testing, please let me know.

**Review by seokho-son — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
